[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
aetos = "0.1.0"
bincode = "2.0.1"
serde = { version = "1.0", features = ["derive"] }
strum = { version = "0.27.2", features = ["derive"] }
